ios_automationName=XCUITest
ios_udid=305F55E2-1FC2-4A68-8107-D8258F17D995
bundleId=com.mutamir.mutamir



android_automationName=UiAutomator2
android_udid=emulator-5554
androidAppPath


appiumURL=http://127.0.0.1:4723
